//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HappyBirthdayApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class view
    {
        public int number { get; set; }
        public string fio { get; set; }
        public System.DateTime day { get; set; }
    }
}
